<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<groupId>org.mission</groupId>
	<artifactId>MissionQA</artifactId>
	<version>1.0-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>8</maven.compiler.source>
		<maven.compiler.target>8</maven.compiler.target>

		<cucumber.version>7.14.0</cucumber.version>
		<selenium.version>4.17.0</selenium.version>
		<testng.version>7.9.0</testng.version>
		<restassured.version>5.4.0</restassured.version>
		<webdrivermanager.version>5.6.3</webdrivermanager.version>
		<jackson.version>2.15.2</jackson.version>
		<commonsio.version>2.15.1</commonsio.version>
		<json.version>20240303</json.version>
	</properties>

	<dependencies>
		<!-- SLF4J logger implementation -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>2.0.13</version>
		</dependency>

		<!-- ================= CUCUMBER ================= -->
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.version}</version>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>${cucumber.version}</version>
		</dependency>

		<!-- ================= TESTNG ================= -->
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${testng.version}</version>
			<scope>test</scope>
		</dependency>

		<!-- ================= SELENIUM ================= -->
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>${selenium.version}</version>
		</dependency>

		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>${webdrivermanager.version}</version>
		</dependency>

		<!-- ================= REST ASSURED ================= -->
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>${restassured.version}</version>
		</dependency>

		<!-- ================= JSON / JACKSON ================= -->
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>${json.version}</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
		</dependency>

		<!-- ================= UTILITIES ================= -->
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>${commonsio.version}</version>
		</dependency>

		<!-- Extent Reports -->
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>5.1.1</version>
		</dependency>

		<!-- Extent Cucumber Adapter -->
		<dependency>
			<groupId>tech.grasshopper</groupId>
			<artifactId>extentreports-cucumber7-adapter</artifactId>
			<version>1.14.0</version>
		</dependency>


	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>net.masterthought</groupId>
				<artifactId>maven-cucumber-reporting</artifactId>
				<version>5.7.8</version>
				<executions>
					<execution>
						<id>generate-cucumber-report</id>
						<phase>verify</phase> <!-- keep verify -->
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<projectName>Mission QA Framework</projectName>
							<outputDirectory>
								${project.build.directory}/cucumber-merged-report</outputDirectory>
							<jsonFiles>
								<param>
									${project.build.directory}/cucumber-json/*.json</param>
							</jsonFiles>
							<buildNumber>1</buildNumber>
							<skip>false</skip>
							<parallelTesting>false</parallelTesting> <!--
							important! -->
						</configuration>
					</execution>
				</executions>
			</plugin>


			<!-- Maven Surefire Plugin for TestNG -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.2.5</version>
			</plugin>

		</plugins>
	</build>

</project>